[build]
  command = "bundle exec jekyll build --source site --destination _site"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
  from = "/2014/03/19/humble-beginnings.html"
  to = "/humble-beginnings/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/03/24/beginner-python-at-bits-hyderabad.html"
  to = "/beginner-python-at-bits-hyderabad/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/03/24/gsoc-proposal-submitted-pens-down.html"
  to = "/gsoc-proposal-submitted-pens-down/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/05/20/entity-embed-a-module-to-allow-any-entity-to-be-embedded.html"
  to = "/entity-embed-a-module-to-allow-any-entity-to-be-embedded/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/05/21/first-week-in-gsoc-getting-started-with-entity-embed.html"
  to = "/first-week-in-gsoc-getting-started-with-entity-embed/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/06/12/gsoc-is-so-much-fun-now-im-interested-in-being-a-gci-mentor.html"
  to = "/gsoc-is-so-much-fun-now-im-interested-in-being-a-gci-mentor/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/06/12/three-weeks-down-with-gsoc-entity-embed-shaping-up-well.html"
  to = "/three-weeks-down-with-gsoc-entity-embed-shaping-up-well/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/08/02/entity-embed-module-demo.html"
  to = "/entity-embed-module-demo/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/09/17/locked-and-loaded-for-gsoc-reunion-summit.html"
  to = "/locked-and-loaded-for-gsoc-reunion-summit/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/11/10/gsoc-reunion-summit-2014-from-my-point-of-view.html"
  to = "/gsoc-reunion-summit-2014-from-my-point-of-view/"
  status = 301
  force = true

[[redirects]]
  from = "/2014/12/01/google-code-in-2014-starts-now.html"
  to = "/google-code-in-2014-starts-now/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/01/23/tips-for-google-summer-of-code.html"
  to = "/tips-for-google-summer-of-code/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/02/16/summary-of-google-code-in-2014-and-welcome-gsoc-2015.html"
  to = "/summary-of-google-code-in-2014-and-welcome-gsoc-2015/"
  status = 301
  force = true

[[redirects]]
  from = "/2015/06/05/drupal-media-in-gsoc-2015.html"
  to = "/drupal-media-in-gsoc-2015/"
  status = 301
  force = true

[context.deploy-preview.environment]
  JEKYLL_ENV = "preview"

[context.branch-deploy.environment]
  JEKYLL_ENV = "preview"
