# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge
permalink: /:title/
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

include:
  - CNAME

# Site settings
title: "Chandan Singh"
description: >
   My views on life, the universe and everything.

email: chandan@chandansingh.net
#blog logo
logo: "/assets/images/cs_logo.png"
# blog cover
cover: "/assets/images/background.jpg"

name: 'Chandan Singh'
author: 'Chandan Singh'
author_image: "/assets/images/author.jpg"

paginate:	10

url: "https://chandansingh.net" # the base hostname & protocol for your site
baseurl: ""

disqus: chandansingh

social:
  - icon:	github
    url:	https://github.com/cs-shadow
    desc:	Find me on GitHub
    share_url:
    share_title:
    share_link:
