#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "date"
require "net/http"
require "optparse"
require "rexml/document"
require "time"
require "tmpdir"
require "uri"
require "yaml"

module GoodreadsSync
  class Error < StandardError; end

  DISPLAY_LIMIT = 12
  SHELVES = %w[currently-reading read].freeze

  module_function

  def text(item, name)
    item.elements[name]&.text.to_s.strip
  end

  def date(value)
    return nil if value.nil? || value.strip.empty?

    Date.parse(value).iso8601
  rescue Date::Error
    Time.parse(value).to_date.iso8601
  rescue ArgumentError
    nil
  end

  def parse_feed(xml, shelf)
    document = REXML::Document.new(xml)
    channel = document.elements["rss/channel"]
    raise Error, "response is not an RSS channel" unless channel

    channel.get_elements("item").filter_map do |item|
      id = text(item, "book_id")
      title = text(item, "title")
      author = text(item, "author_name")
      next if id.empty? || title.empty? || author.empty?

      finished_date = shelf == "read" ? date(text(item, "user_read_at")) : nil
      activity_date =
        if shelf == "read"
          finished_date || date(text(item, "user_date_added")) || date(text(item, "pubDate"))
        else
          date(text(item, "user_date_added")) || date(text(item, "pubDate"))
        end
      cover = %w[book_large_image_url book_medium_image_url book_image_url].lazy
        .map { |name| text(item, name) }.find { |value| !value.empty? }
      link = text(item, "link")

      {
        "id" => id,
        "title" => title,
        "author" => author,
        "status" => shelf,
        "activity_date" => activity_date,
        "finished_date" => finished_date,
        "cover_url" => cover,
        "goodreads_url" => link.empty? ? "https://www.goodreads.com/book/show/#{id}" : link
      }.compact
    end
  rescue REXML::ParseException => e
    raise Error, "invalid XML: #{e.message}"
  end

  def parse_csv(path)
    CSV.table(path, headers: true, header_converters: ->(name) { name.downcase.gsub(/\W+/, "_").to_sym }).filter_map do |row|
      shelf = row[:exclusive_shelf].to_s
      next unless SHELVES.include?(shelf)

      id = row[:book_id].to_s
      next if id.empty?

      finished_date = shelf == "read" ? date(row[:date_read].to_s) : nil
      {
        "id" => id,
        "title" => row[:title].to_s,
        "author" => row[:author].to_s,
        "status" => shelf,
        "activity_date" => finished_date || date(row[:date_added].to_s),
        "finished_date" => finished_date,
        "goodreads_url" => "https://www.goodreads.com/book/show/#{id}"
      }.compact
    end
  rescue CSV::MalformedCSVError => e
    raise Error, "invalid CSV: #{e.message}"
  end

  def fetch(uri)
    response = Net::HTTP.get_response(uri)
    raise Error, "Goodreads returned HTTP #{response.code}" unless response.is_a?(Net::HTTPSuccess)
    raise Error, "Goodreads returned an empty response" if response.body.to_s.strip.empty?

    response.body
  end

  def normalize(books)
    unique = {}
    books.each do |book|
      existing = unique[book.fetch("id")]
      unique[book.fetch("id")] = book if existing.nil? || book["status"] == "currently-reading"
    end
    unique.values.sort_by do |book|
      [book["activity_date"] ? 0 : 1, book["activity_date"] ? -Date.iso8601(book["activity_date"]).jd : 0, book["id"]]
    end
  end

  def serialized(books)
    "# Generated by scripts/sync_goodreads.rb. Do not edit.\n" + YAML.dump(books)
  end

  def displayed(books)
    normalize(books).first(DISPLAY_LIMIT)
  end

  def write_if_changed(destination, content)
    return false if File.exist?(destination) && File.read(destination) == content

    directory = File.dirname(destination)
    Dir.mkdir(directory) unless Dir.exist?(directory)
    temporary = File.join(directory, ".#{File.basename(destination)}.tmp")
    File.write(temporary, content)
    File.rename(temporary, destination)
    true
  ensure
    File.delete(temporary) if temporary && File.exist?(temporary)
  end
end

def main(arguments)
  options = {
    destination: File.expand_path("../site/_data/goodreads_books.yml", __dir__)
  }
  OptionParser.new do |parser|
    parser.banner = "Usage: sync_goodreads.rb [--user-id ID | --csv PATH] [--output PATH]"
    parser.on("--user-id ID", "Goodreads numeric user ID") { |value| options[:user_id] = value }
    parser.on("--csv PATH", "Import a Goodreads library export") { |value| options[:csv] = value }
    parser.on("--output PATH", "Generated YAML destination") { |value| options[:destination] = value }
  end.parse!(arguments)

  books =
    if options[:csv]
      GoodreadsSync.parse_csv(options[:csv])
    else
      user_id = options[:user_id] || ENV["GOODREADS_USER_ID"]
      raise GoodreadsSync::Error, "GOODREADS_USER_ID is required" unless user_id&.match?(/\A\d+\z/)

      GoodreadsSync::SHELVES.flat_map do |shelf|
        uri = URI("https://www.goodreads.com/review/list_rss/#{user_id}?shelf=#{shelf}")
        GoodreadsSync.parse_feed(GoodreadsSync.fetch(uri), shelf)
      end
    end

  raise GoodreadsSync::Error, "Goodreads returned no usable books" if books.empty?

  changed = GoodreadsSync.write_if_changed(
    options[:destination],
    GoodreadsSync.serialized(GoodreadsSync.displayed(books))
  )
  puts changed ? "Updated #{options[:destination]}" : "Reading data is already current"
  0
rescue GoodreadsSync::Error, Errno::ENOENT, SocketError, SystemCallError => e
  warn "Goodreads sync failed: #{e.message}"
  1
end

exit main(ARGV) if $PROGRAM_NAME == __FILE__
